# Generated by Django 6.0.6 on 2026-06-17 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CITY", "City"),
                            ("DISTRICT", "District"),
                            ("REGION", "Region"),
                            ("QUARTIER", "Quartier"),
                        ],
                        default="CITY",
                        max_length=20,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Territories",
            },
        ),
        migrations.CreateModel(
            name="TerritorialMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "trend",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change vs previous period",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["name", "timestamp"], name="territories_name_02ce45_idx"
                    )
                ],
            },
        ),
    ]
