# Generated by Django 6.0.6 on 2026-06-18 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="area_km2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="territory",
            name="country",
            field=models.CharField(default="France", max_length=100),
        ),
        migrations.AddField(
            model_name="territory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="population",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="territory",
            name="region_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="territory",
            name="boundary",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="territory",
            name="type",
            field=models.CharField(
                choices=[
                    ("CITY", "Ville"),
                    ("COMMUNE", "Commune"),
                    ("DEPARTEMENT", "Département"),
                    ("PROVINCE", "Province"),
                    ("REGION", "Région"),
                    ("DISTRICT", "District"),
                    ("SPECIAL", "Zone spéciale"),
                ],
                default="CITY",
                max_length=20,
            ),
        ),
    ]
